### ISSUE TITLE
Borders and Decorations

### ISSUE THREAD

**Issue by Sainan123** [Sainan123/ASCII-Art-Generator-SainanBI-CDOF2#3]
Allow users to add borders or other decorative elements to their ASCII art.

**Comment by Jintao0329** [comment]
I add a  function on allowing users to add borders to their ASCII art.

**Comment by Sainan123** [comment]
Could you please explain more on how did you work on that?

**Comment by Jintao0329** [comment]
I've added a function add_border which takes the ASCII art and a border character, then adds a border made of that character around the ASCII art. The main function has been updated to ask the user if they want to add a border and, if so, what character to use for the border.

**Comment by Sainan123** [comment]
okey, thanks so much!! I will verify it.
